name: Fugitive Azure DevOps
on: [push, pull_request]
jobs:
  Vader:
    strategy:
      matrix:
        vim:
          - package: vim
            bin: vim
          - package: neovim
            bin: nvim
    runs-on: ubuntu-latest
    steps:
      - name: Git clone Vader
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader.vim
      - name: Git clone Fugitive
        uses: actions/checkout@v2
        with:
          repository: tpope/vim-fugitive
          path: vim-fugitive
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: fugitive-azure-devops.vim
      - name: Install packages
        run: sudo apt-get install -y ${{ matrix.vim.package }} curl
      - name: Run vader against ${{ matrix.vim.package }}
        run: ${{ matrix.vim.bin }} -Es -Nu fugitive-azure-devops.vim/tests/vimrc -c "Vader! fugitive-azure-devops.vim/tests/*" 2>&1
